spring.application.name=sistema-vendas
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema-vendas
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# JWT
# Em producao, configure JWT_SECRET como variavel de ambiente.
jwt.secret=${JWT_SECRET:chave-super-secreta-com-pelo-menos-32-caracteres}
jwt.expiracao=86400000